### PR TITLE
Upgrade to next.js 9

### PR DESCRIPTION
**Pull request by hstove**
This PR implements the changes to get app.co upgraded to [Next v9](https://nextjs.org/blog/next-9), which has some great changes and could lay the groundwork for easily porting to TypeScript.

The upgrade was pretty annoying. Pages wouldn't compile, and there was some very odd `TypeError` messages being logged, but they didn't make much sense or have any backtrace. After a ton of random commenting out of code, I was able to narrow it down.

It turns out that something to do with the new Next compiler has issues with object destructuring. I had to change a bunch of destructuring calls to not be destructured, which results in uglier code, but now it compiles and runs.

There were a few other changes, like no more `<Container>` in `_app.js`, no more `prefetch` (its on by default), and a few other small things.

@kyranjamie , would you mind going through the app and doing a pass, making sure I didn't miss any pages that might have this compilation error? As well as a run-through of the code changes.

### CODE REVIEW

**Comment by kyranjamie** [comment]
Nice step towards being able to use TypeScript 💪 

I'm having some mixed behaviour with this, though. Sometimes I'm getting a  404 visiting `/` or `/admin`, and then othertimes it'll refresh itself and work.

**Comment by hstove** [comment]
Thanks, let me check on that admin page and make sure there are no new errors.

Also, I successfully converted our first component to TS! It took some tweaking, and didn't work out of the box. I had to add `@zeit/next-typescript`, even though you get a warning that you don't need it. We definitely need it; the pages wouldn't resolve without that.

**Comment by kyranjamie** [comment]
Great stuff, hoping we can run a:

```bash
find {pages,components,containers} -name "*.js" -exec sh -c 'mv "$0" "${0%.js}.tsx"' {} \;
```
soon

**Comment by hstove** [comment]
Thanks @Timer for chiming in. If I remove `@zeit/next-typescript`, and visit `/faq` (the only component converted to TS), then it 404s, and I don't see any errors, it seems like it just doesn't resolve the file.

**Comment by Timer** [comment]
@hstove It looks like you didn't update your `pageExtensions` in `next.config.js` to include `.ts` and `.tsx`.

**Comment by hstove** [comment]
Thanks, @Timer . That solves the second issue I reported!

**Comment by Timer** [comment]
I'm guessing the destructing not working is due to a bad Babel configuration.

Can you please remove these two plugins:
```
    "@babel/plugin-transform-regenerator",
    "@babel/plugin-transform-runtime",
```

**Comment by hstove** [comment]
@Timer that's actually funny timing. I ended up figuring that out just now, and I hadn't seen your comment yet. I removed those, and it fixed the issue. Thank you for spending your time helping us out.

This PR should be good to merge now.

**Comment by hstove** [comment]
Just kidding - another issue (with our code) is that we have files in `/pages` that don't default export React components, which breaks `next build`. Those files all need to be migrated to `components` or `containers`.

~~~
pages/home
pages/mining/apps/table-section
pages/mining/faq/faq-section
pages/mining/sections/faq
pages/mining/sections/hero
pages/mining/sections/how-much-earn
pages/mining/sections/pioneers
pages/mining/sections/ranking
pages/mining/sections/ready-apps
pages/mining/sections/start-app-mining
pages/mining/shared
pages/mining/starter-kit-modal
pages/mining/updates-modal
~~~

cc @kyranjamie - I mentioned this in your other PR, and it looks like doing this will cause actual build errors in Next 9.

**Comment by hstove** [comment]
@timstackblock , I'm requesting your review on this. This PR only upgrades a dependency of app.co, and doesn't introduce any functionality changes. We just want to make sure the app works normally. The effected areas would really only be page loads, and not any features after a page loads. So, simply clicking links around the app should suffice.

This is not an urgent request, I just wanted to pass it by you first.

**Comment by timstackblock** [comment]
@hstove no problem I will verify that pages still load as expected after the upgrade.

**Comment by hstove** [comment]
Hey @timstackblock , just wanted to follow up here. Were you able to do any testing?

**Comment by kyranjamie** [comment]
This'll be really great to get merged in, so I can rebase the maker portal release branch. Have found a few features that'd be nice to use that came out with v9, e.g. `useRouter` hook

**Pull request merged**
