### PR TITLE
feat: redirect to blockstack apps page on www2.blockstack.org

### PR DESCRIPTION
**Pull request by kyranjamie**

### CODE REVIEW

**Comment by hstove** [comment]
@kyranjamie did you mean to add the `gensync` package?

**Comment by hstove** [comment]
It's good to have this PR ready for when we want to do this, but IMO that page just isn't ready yet. Although I think that's understood by all involved.

**Comment by kyranjamie** [comment]
`gensync` is intentional, without I get

```
[ error ] ./node_modules/next/dist/client/next-dev.js
Error: Cannot find module 'gensync'
Require stack:
- /Users/kyran/dev/blockstack/app.co/node_modules/next/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/core/lib/gensync-utils/async.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/core/lib/config/caching.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/core/lib/config/files/utils.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/core/lib/config/files/package.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/core/lib/config/files/index.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/node_modules/@babel/plugin-transform-modules-commonjs/node_modules/@babel/core/lib/index.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/dist/build/babel/plugins/commonjs.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
- /Users/kyran/dev/blockstack/app.co/node_modules/loader-runner/lib/loadLoader.js
- /Users/kyran/dev/blockstack/app.co/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/kyran/dev/blockstack/app.co/node_modules/webpack/lib/NormalModule.js
- /Users/kyran/dev/blockstack/app.co/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/kyran/dev/blockstack/app.co/node_modules/webpack/lib/Compiler.js
- /Users/kyran/dev/blockstack/app.co/node_modules/webpack/lib/webpack.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/dist/server/hot-reloader.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/dist/server/next-dev-server.js
- /Users/kyran/dev/blockstack/app.co/node_modules/next/dist/server/next.js
- /Users/kyran/dev/blockstack/app.co/server.js
```

**Comment by hstove** [comment]
Huh, ok!

It sounds like we're OK with redirecting to this new page, however, we also need to solve for client-side routing. I haven't tested, but I'm assuming this wouldn't work for client-side routing. Can you add some logic to redirect on the client-side? Or, just LMK if you'd rather me take this on, so that you can focus totally on the wallet.

**Comment by kyranjamie** [comment]
@hstove this change handles the clientside routing

```   
   if (platform === 'blockstack') {
      window.location.href = 'https://www2.blockstack.org/apps';
    }
```

**Comment by hstove** [comment]
Oh, duh, thanks!

**Pull request merged**
