### PR TITLE
Analytics event tracking

### PR DESCRIPTION
**Pull request by hstove**
This PR addresses #85 and #427 .

All events should be tracked that are described in #427 .

I'm assigning to @markmhx to QA this. Basically, click around and make sure events are fired in Segment.

### CODE REVIEW

**Comment by markmhx** [comment]
We don't seem to be capturing the page `title` value correctly here – this one for example should be "BitTube – App.co, The Universal Dapp Store" not just "App.co, The Universal Dapp Store"

screen shot 2019-01-31 at 16 09 55

**Comment by markmhx** [comment]
We can keep this "View Mining Landing Page" event if you'd like, but note that it's a bit redundant with the default page view tracking (for `/mining`), which we can use as easily for funnel reports:

screen shot 2019-01-31 at 16 14 03

**Comment by markmhx** [comment]
What do you think of adding these following events as part of this implementation? I'd also be happy to tackle them in separate issues:

- Search queries
- Email submissions for "get updates" prompt around App.co generically (outside of App Mining)

**Comment by markmhx** [comment]
This may not have a practical consequence, but I noticed on staging that these apps link to the production app.co site's app profiles instead of the staging ones:

screen shot 2019-01-31 at 16 31 04

**Comment by markmhx** [comment]
Given our intent to treat the "subscribe for updates" prompt differently than the "get starter kit" one, should we track the former with more specific event names (e.g. "Open App Mining Updates Subscription Modal")? Otherwise we won't be able to distinguish which prompt gets more usage:

screen shot 2019-01-31 at 16 32 19
screen shot 2019-01-31 at 16 32 21

**Comment by markmhx** [comment]
@hstove I've completed my review. Other than the above comments, this looks great 💪🏻

**Comment by hstove** [comment]
Great feedback Mark!

> What do you think of adding these following events as part of this implementation? I'd also be happy to tackle them in separate issues:

Added 👍

> Given our intent to treat the "subscribe for updates" prompt differently than the "get starter kit" one, should we track the former with more specific event names (e.g. "Open App Mining Updates Subscription Modal")? Otherwise we won't be able to distinguish which prompt gets more usage:

I don't have a way of distinguishing which one is shown right now, so I think we should hold off until we make that change.

---

Every other issue you brought up should be fixed.

**Comment by markmhx** [comment]
@hstove Could we redeploy staging here? https://app-co-staging-pr-444.herokuapp.com/ appears dead now.

**Comment by hstove** [comment]
Yes, the heroku PR apps get killed if there is a week of inactivity. I just triggered a rebuild, check in 10 minutes (it'll say it was deployed right here in Github).

**Comment by markmhx** [comment]
These changes all look good 💪🏻

Only one I don't see firing still is https://github.com/blockstack/app.co/pull/444#issuecomment-459386615

Otherwise, good to ⛴

**Comment by hstove** [comment]
@markmhx good catch. Fixed.

**Comment by markmhx** [comment]
@hstove Fix works for me 💪🏻

**Pull request merged**
